Add searchbar to list page
valamuri2020/NewVision pull request #6
Opened 2021-03-28 00:23 UTC by Kshitij-Kumar123

select different universities to add in your list and automatically add data. 
currently gets a hardcoded variable for data, which will be replaced

2021-04-02 16:24 UTC, Kshitij-Kumar123 commented
Do not merge this branch. This branch is work in progress

2021-04-17 16:31 UTC, Kshitij-Kumar123 commented
focusing on functionality right now. css changes for the horizontal dashboard cards to be done in a future pr

2021-04-17 18:06 UTC, valamuri2020 requested changes

2021-04-17 18:06 UTC, valamuri2020 commented on src/components/Navbar/Navbar.jsx
> +            <Dropdown.Item onClick={handleLogOut}>Sign Out</Dropdown.Item>
put signout below user email

2021-04-17 18:06 UTC, valamuri2020 commented on src/components/list/listCard.jsx
> +          <Input value={selectedCollege?.["ACTENMID"]} onChange={(e) => handleChange(e.target.value, 'ACTENMID')}/>
please change this to acceptance data from ACTENMID data

2021-04-17 18:58 UTC, valamuri2020 approved these changes

2021-04-17 18:58 UTC, merged